name: Build Docs

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    branches: [ master ]
    paths:
    - "docs/**"

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DotNetVersion }}

    - uses: nikeee/docfx-action@v1.0.0
      name: Build Documentation
      with:
        args: docs/docfx.json

    - name: Deploy Docs
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        BRANCH: gh-pages
        FOLDER: ./docs/_site